apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: chat-app
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: mongodb-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
